module.exports = [
  // -------------------------------------------------------------
  // 2020s (25+ songs)
  // -------------------------------------------------------------
  {
    title: 'Chaleya',
    movie: 'Jawan',
    singers: ['Arijit Singh', 'Shilpa Rao'],
    artists: ['Shah Rukh Khan', 'Nayanthara'],
    composers: ['Anirudh Ravichander'],
    lyricist: 'Kumaar',
    releaseYear: 2023,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ishq mein dil bana hai', 'Chaleya Jawan']
  },
  {
    title: 'O Bedardeya',
    movie: 'Tu Jhoothi Main Makkaar',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Shraddha Kapoor'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2023,
    genre: ['Sad', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['O Bedardya']
  },
  {
    title: 'Tere Vaaste',
    movie: 'Zara Hatke Zara Bachke',
    singers: ['Varun Jain', 'Sachin-Jigar', 'Shadab Faridi', 'Altamash Faridi'],
    artists: ['Vicky Kaushal', 'Sara Ali Khan'],
    composers: ['Sachin-Jigar'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2023,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tere Vaste Falak Se']
  },
  {
    title: 'Phir Aur Kya Chahiye',
    movie: 'Zara Hatke Zara Bachke',
    singers: ['Arijit Singh', 'Sachin-Jigar'],
    artists: ['Vicky Kaushal', 'Sara Ali Khan'],
    composers: ['Sachin-Jigar'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2023,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tu hai toh mujhe phir aur kya chahiye']
  },
  {
    title: 'Heeriye',
    movie: 'Single',
    singers: ['Jasleen Royal', 'Arijit Singh'],
    artists: ['Dulquer Salmaan', 'Jasleen Royal'],
    composers: ['Jasleen Royal'],
    lyricist: 'Aditya Sharma',
    releaseYear: 2023,
    genre: ['Romantic', 'Indie Hindi'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Heeriye Heeriye Aa']
  },
  {
    title: 'Satranga',
    movie: 'Animal',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Rashmika Mandanna'],
    composers: ['Shreyas Puranik'],
    lyricist: 'Siddharth-Garima',
    releaseYear: 2023,
    genre: ['Sad', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Satranga Ishq']
  },
  {
    title: 'Arjan Vailly',
    movie: 'Animal',
    singers: ['Bhupinder Babbal'],
    artists: ['Ranbir Kapoor'],
    composers: ['Manan Bhardwaj'],
    lyricist: 'Bhupinder Babbal',
    releaseYear: 2023,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Arjan Velly', 'Animal Punjabi Song']
  },
  {
    title: 'Jhoome Jo Pathaan',
    movie: 'Pathaan',
    singers: ['Arijit Singh', 'Sukriti Kakar', 'Vishal-Shekhar'],
    artists: ['Shah Rukh Khan', 'Deepika Padukone'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Kumaar',
    releaseYear: 2023,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Jhoome Jo Pathan']
  },
  {
    title: 'Besharam Rang',
    movie: 'Pathaan',
    singers: ['Shilpa Rao', 'Caralisa Monteiro', 'Vishal-Shekhar'],
    artists: ['Deepika Padukone', 'Shah Rukh Khan'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Kumaar',
    releaseYear: 2022,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Besharam Rang Kahan Dekha Duniya Walon Ne']
  },
  {
    title: 'Apna Bana Le',
    movie: 'Bhediya',
    singers: ['Arijit Singh', 'Sachin-Jigar'],
    artists: ['Varun Dhawan', 'Kriti Sanon'],
    composers: ['Sachin-Jigar'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2022,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Apna Bana Le Piya']
  },
  {
    title: 'Kesariya',
    movie: 'Brahmastra',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Alia Bhatt'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2022,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kesariya Tera Ishq Hai Piya']
  },
  {
    title: 'Naatu Naatu (Hindi)',
    movie: 'RRR',
    singers: ['Rahul Sipligunj', 'Kaala Bhairava'],
    artists: ['Ram Charan', 'Jr NTR'],
    composers: ['M. M. Keeravani'],
    lyricist: 'Riya Mukherjee',
    releaseYear: 2022,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Naacho Naacho', 'Natu Natu']
  },
  {
    title: 'Dil',
    movie: 'Ek Villain Returns',
    singers: ['Raghav Chaitanya'],
    artists: ['John Abraham', 'Disha Patani'],
    composers: ['Kaushik-Guddu'],
    lyricist: 'Kunaal Vermaa',
    releaseYear: 2022,
    genre: ['Sad', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Na Jaaneya']
  },
  {
    title: 'Pasoori',
    movie: 'Coke Studio',
    singers: ['Ali Sethi', 'Shae Gill'],
    artists: ['Ali Sethi', 'Shae Gill'],
    composers: ['Xulfi', 'Ali Sethi'],
    lyricist: 'Ali Sethi',
    releaseYear: 2022,
    genre: ['Indie Hindi'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Pasoori Nu']
  },
  {
    title: 'Maan Meri Jaan',
    movie: 'Champagne Talk',
    singers: ['King'],
    artists: ['King'],
    composers: ['Saurabh Lokhande'],
    lyricist: 'King',
    releaseYear: 2022,
    genre: ['Romantic', 'Indie Hindi'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tu Maan Meri Jaan']
  },
  {
    title: 'Calm Down (Hindi Remix)',
    movie: 'Single',
    singers: ['Rema', 'Selena Gomez'],
    artists: ['Rema', 'Selena Gomez'],
    composers: ['Rema'],
    lyricist: 'Rema',
    releaseYear: 2022,
    genre: ['Party', 'Indie Hindi'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Calm Down Baby']
  },
  {
    title: 'Srivalli (Hindi)',
    movie: 'Pushpa: The Rise',
    singers: ['Javed Ali'],
    artists: ['Allu Arjun', 'Rashmika Mandanna'],
    composers: ['Devi Sri Prasad'],
    lyricist: 'Raqueeb Alam',
    releaseYear: 2021,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Teri Jhalak Asharfi']
  },
  {
    title: 'Oo Antava (Hindi)',
    movie: 'Pushpa: The Rise',
    singers: ['Kanika Kapoor'],
    artists: ['Allu Arjun', 'Samantha Ruth Prabhu'],
    composers: ['Devi Sri Prasad'],
    lyricist: 'Raqueeb Alam',
    releaseYear: 2021,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Oo Bolega Ya Oo Oo Bolega']
  },
  {
    title: 'Raataan Lambiyan',
    movie: 'Shershaah',
    singers: ['Jubin Nautiyal', 'Asees Kaur'],
    artists: ['Sidharth Malhotra', 'Kiara Advani'],
    composers: ['Tanishk Bagchi'],
    lyricist: 'Tanishk Bagchi',
    releaseYear: 2021,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ratan Lambiyan', 'Teri Meri Gallan']
  },
  {
    title: 'Ranjha',
    movie: 'Shershaah',
    singers: ['B Praak', 'Jasleen Royal'],
    artists: ['Sidharth Malhotra', 'Kiara Advani'],
    composers: ['Jasleen Royal'],
    lyricist: 'Anvita Dutt',
    releaseYear: 2021,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Chup Maahi Chup Hai Ranjha']
  },
  {
    title: 'Lut Gaye',
    movie: 'Single',
    singers: ['Jubin Nautiyal'],
    artists: ['Emraan Hashmi', 'Yukti Thareja'],
    composers: ['Tanishk Bagchi'],
    lyricist: 'Manoj Muntashir',
    releaseYear: 2021,
    genre: ['Sad', 'Indie Hindi'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Lut Gaye Hum Teri Mohabbat Mein']
  },
  {
    title: 'Dil Ko Karaar Aaya',
    movie: 'Single',
    singers: ['Neha Kakkar', 'Yasser Desai'],
    artists: ['Sidharth Shukla', 'Neha Sharma'],
    composers: ['Rajat Nagpal'],
    lyricist: 'Rana Sotal',
    releaseYear: 2020,
    genre: ['Romantic', 'Indie Hindi'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Ko Karar Aaya']
  },
  {
    title: 'Shayad',
    movie: 'Love Aaj Kal',
    singers: ['Arijit Singh'],
    artists: ['Kartik Aaryan', 'Sara Ali Khan'],
    composers: ['Pritam'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2020,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Shayad Kabhi Na Keh Saku Main Tumko']
  },
  {
    title: 'Tera Ban Jaunga',
    movie: 'Kabir Singh',
    singers: ['Akhil Sachdeva', 'Tulsi Kumar'],
    artists: ['Shahid Kapoor', 'Kiara Advani'],
    composers: ['Akhil Sachdeva'],
    lyricist: 'Kumaar',
    releaseYear: 2019,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Main Tera Ban Jaunga']
  },
  {
    title: 'Bekhayali',
    movie: 'Kabir Singh',
    singers: ['Sachet Tandon'],
    artists: ['Shahid Kapoor', 'Kiara Advani'],
    composers: ['Sachet-Parampara'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2019,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Bekhayali Mein Bhi Tera']
  },
  {
    title: 'Tujhe Kitna Chahne Lage',
    movie: 'Kabir Singh',
    singers: ['Arijit Singh'],
    artists: ['Shahid Kapoor', 'Kiara Advani'],
    composers: ['Mithoon'],
    lyricist: 'Mithoon',
    releaseYear: 2019,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tujhe Kitna Chahne Lage Hum']
  },
  
  // -------------------------------------------------------------
  // 2010s (35+ songs)
  // -------------------------------------------------------------
  {
    title: 'Ghar More Pardesiya',
    movie: 'Kalank',
    singers: ['Shreya Ghoshal', 'Vaishali Mhade'],
    artists: ['Alia Bhatt', 'Madhuri Dixit'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2019,
    genre: ['Classical', 'Bollywood'],
    difficulty: 4,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ghar More Pardesiya']
  },
  {
    title: 'Ae Watan',
    movie: 'Raazi',
    singers: ['Arijit Singh'],
    artists: ['Alia Bhatt'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Gulzar',
    releaseYear: 2018,
    genre: ['Devotional', 'Bollywood'], // using Devotional as Patriotic
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ae Watan Mere Watan Aabad Rahe Tu']
  },
  {
    title: 'Dil Diyan Gallan',
    movie: 'Tiger Zinda Hai',
    singers: ['Atif Aslam'],
    artists: ['Salman Khan', 'Katrina Kaif'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2017,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kachchi Doriyon']
  },
  {
    title: 'Swag Se Swagat',
    movie: 'Tiger Zinda Hai',
    singers: ['Vishal Dadlani', 'Neha Bhasin'],
    artists: ['Salman Khan', 'Katrina Kaif'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2017,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Swag Se Karenge Sabka Swagat']
  },
  {
    title: 'Enna Sona',
    movie: 'OK Jaanu',
    singers: ['Arijit Singh'],
    artists: ['Aditya Roy Kapur', 'Shraddha Kapoor'],
    composers: ['A. R. Rahman'],
    lyricist: 'Gulzar',
    releaseYear: 2017,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Enna Sona Kyun Rab Ne Banaya']
  },
  {
    title: 'Ae Dil Hai Mushkil',
    movie: 'Ae Dil Hai Mushkil',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Anushka Sharma', 'Aishwarya Rai Bachchan'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2016,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['ADHM Title Track']
  },
  {
    title: 'Channa Mereya',
    movie: 'Ae Dil Hai Mushkil',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Anushka Sharma'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2016,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Accha Chalta Hoon', 'Channa Mereya Mereya']
  },
  {
    title: 'Bulleya',
    movie: 'Ae Dil Hai Mushkil',
    singers: ['Amit Mishra', 'Shilpa Rao'],
    artists: ['Ranbir Kapoor', 'Aishwarya Rai Bachchan'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2016,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Meri Rooh Ka Parinda']
  },
  {
    title: 'Tere Sang Yaara',
    movie: 'Rustom',
    singers: ['Atif Aslam'],
    artists: ['Akshay Kumar', 'Ileana D\'Cruz'],
    composers: ['Arko'],
    lyricist: 'Manoj Muntashir',
    releaseYear: 2016,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['O Karam Khudaya Hai']
  },
  {
    title: 'Kaala Chashma',
    movie: 'Baar Baar Dekho',
    singers: ['Amar Arshi', 'Badshah', 'Neha Kakkar'],
    artists: ['Sidharth Malhotra', 'Katrina Kaif'],
    composers: ['Prem-Hardeep', 'Badshah'],
    lyricist: 'Amrik Singh',
    releaseYear: 2016,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kala Chashma']
  },
  {
    title: 'Nashe Si Chadh Gayi',
    movie: 'Befikre',
    singers: ['Arijit Singh'],
    artists: ['Ranveer Singh', 'Vaani Kapoor'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Jaideep Sahni',
    releaseYear: 2016,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Nashe Se Chadh Gayi']
  },
  {
    title: 'Kar Gayi Chull',
    movie: 'Kapoor & Sons',
    singers: ['Badshah', 'Fazilpuria', 'Sukriti Kakar', 'Neha Kakkar'],
    artists: ['Sidharth Malhotra', 'Alia Bhatt'],
    composers: ['Badshah', 'Amaal Mallik'],
    lyricist: 'Badshah',
    releaseYear: 2016,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ladki Beautiful Kar Gayi Chull']
  },
  {
    title: 'Soch Na Sake',
    movie: 'Airlift',
    singers: ['Arijit Singh', 'Tulsi Kumar', 'Amaal Mallik'],
    artists: ['Akshay Kumar', 'Nimrat Kaur'],
    composers: ['Amaal Mallik'],
    lyricist: 'Kumaar',
    releaseYear: 2016,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tenu Itna Main Pyaar Karaan']
  },
  {
    title: 'Bol Do Na Zara',
    movie: 'Azhar',
    singers: ['Armaan Malik'],
    artists: ['Emraan Hashmi', 'Nargis Fakhri'],
    composers: ['Amaal Mallik'],
    lyricist: 'Rashmi Virag',
    releaseYear: 2016,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Bol Do Na Zara Dil Mein Jo Hai Chhipa']
  },
  {
    title: 'Agar Tum Saath Ho',
    movie: 'Tamasha',
    singers: ['Alka Yagnik', 'Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Deepika Padukone'],
    composers: ['A. R. Rahman'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2015,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Pal Bhar Theher Jaao']
  },
  {
    title: 'Gerua',
    movie: 'Dilwale',
    singers: ['Arijit Singh', 'Antara Mitra'],
    artists: ['Shah Rukh Khan', 'Kajol'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2015,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Rang De Tu Mohe Gerua']
  },
  {
    title: 'Gallan Goodiyaan',
    movie: 'Dil Dhadakne Do',
    singers: ['Yashita Sharma', 'Manish Kumar Tipu', 'Farhan Akhtar', 'Shankar Mahadevan', 'Sukhwinder Singh'],
    artists: ['Anil Kapoor', 'Shefali Shah', 'Priyanka Chopra', 'Ranveer Singh', 'Anushka Sharma', 'Farhan Akhtar'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2015,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Gallan Goodiyan']
  },
  {
    title: 'Sun Saathiya',
    movie: 'ABCD 2',
    singers: ['Priya Saraiya', 'Divya Kumar'],
    artists: ['Varun Dhawan', 'Shraddha Kapoor'],
    composers: ['Sachin-Jigar'],
    lyricist: 'Priya Saraiya',
    releaseYear: 2015,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Sun Saathiya Mahiya']
  },
  {
    title: 'Muskurane',
    movie: 'CityLights',
    singers: ['Arijit Singh'],
    artists: ['Rajkummar Rao', 'Patralekha'],
    composers: ['Jeet Gannguli'],
    lyricist: 'Rashmi Singh',
    releaseYear: 2014,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Muskurane Ki Wajah Tum Ho']
  },
  {
    title: 'Suno Na Sangemarmar',
    movie: 'Youngistaan',
    singers: ['Arijit Singh'],
    artists: ['Jackky Bhagnani', 'Neha Sharma'],
    composers: ['Jeet Gannguli'],
    lyricist: 'Kausar Munir',
    releaseYear: 2014,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Suno Na Sang e Marmar']
  },
  {
    title: 'London Thumakda',
    movie: 'Queen',
    singers: ['Labh Janjua', 'Sonu Kakkad', 'Neha Kakkar'],
    artists: ['Kangana Ranaut'],
    composers: ['Amit Trivedi'],
    lyricist: 'Anvita Dutt',
    releaseYear: 2014,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['London Thumakda']
  },
  {
    title: 'Aaj Phir',
    movie: 'Hate Story 2',
    singers: ['Arijit Singh', 'Samira Koppikar'],
    artists: ['Jay Bhanushali', 'Surveen Chawla'],
    composers: ['Arko'],
    lyricist: 'Aziz Qaisi',
    releaseYear: 2014,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Aaj Phir Tum Pe Pyaar Aaya Hai']
  },
  {
    title: 'Tum Hi Ho',
    movie: 'Aashiqui 2',
    singers: ['Arijit Singh'],
    artists: ['Aditya Roy Kapur', 'Shraddha Kapoor'],
    composers: ['Mithoon'],
    lyricist: 'Mithoon',
    releaseYear: 2013,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kyunki Tum Hi Ho']
  },
  {
    title: 'Ilahi',
    movie: 'Yeh Jawaani Hai Deewani',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2013,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ilahi Mera Jee Aaye Aaye']
  },
  {
    title: 'Badtameez Dil',
    movie: 'Yeh Jawaani Hai Deewani',
    singers: ['Benny Dayal', 'Shefali Alvares'],
    artists: ['Ranbir Kapoor', 'Deepika Padukone'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2013,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Batameez Dil']
  },
  {
    title: 'Balam Pichkari',
    movie: 'Yeh Jawaani Hai Deewani',
    singers: ['Vishal Dadlani', 'Shalmali Kholgade'],
    artists: ['Ranbir Kapoor', 'Deepika Padukone'],
    composers: ['Pritam'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2013,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Balam Pichkari Jo Tune Mujhe Maari']
  },
  {
    title: 'Lat Lag Gayee',
    movie: 'Race 2',
    singers: ['Benny Dayal', 'Shalmali Kholgade'],
    artists: ['Saif Ali Khan', 'Jacqueline Fernandez'],
    composers: ['Pritam'],
    lyricist: 'Mayur Puri',
    releaseYear: 2013,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mujhe To Teri Lat Lag Gayee']
  },
  {
    title: 'Phir Le Aya Dil',
    movie: 'Barfi!',
    singers: ['Arijit Singh'],
    artists: ['Ranbir Kapoor', 'Priyanka Chopra', 'Ileana D\'Cruz'],
    composers: ['Pritam'],
    lyricist: 'Sayeed Quadri',
    releaseYear: 2012,
    genre: ['Sad', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Phir Le Aaya Dil']
  },
  {
    title: 'Tum Se Hi',
    movie: 'Jab We Met',
    singers: ['Mohit Chauhan'],
    artists: ['Shahid Kapoor', 'Kareena Kapoor'],
    composers: ['Pritam'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2007, // Placed in 2010s block by user request conceptually, but fixing year
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tumse Hi Tum Se Hi']
  },
  {
    title: 'Mauja Hi Mauja',
    movie: 'Jab We Met',
    singers: ['Mika Singh'],
    artists: ['Shahid Kapoor', 'Kareena Kapoor'],
    composers: ['Pritam'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2007,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mauja Hi Mauja']
  },
  {
    title: 'Ye Ishq Hai',
    movie: 'Jab We Met',
    singers: ['Shreya Ghoshal'],
    artists: ['Kareena Kapoor', 'Shahid Kapoor'],
    composers: ['Pritam'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2007,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Haan Hai Koi To Wajah']
  },
  {
    title: 'Badri Ki Dulhania (Title Track)',
    movie: 'Badrinath Ki Dulhania',
    singers: ['Dev Negi', 'Neha Kakkar', 'Monali Thakur', 'Ikka'],
    artists: ['Varun Dhawan', 'Alia Bhatt'],
    composers: ['Tanishk Bagchi'],
    lyricist: 'Shabbir Ahmed',
    releaseYear: 2017,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Badri Ki Dulhania']
  },
  {
    title: 'Despacito (Hindi Cover)',
    movie: 'Single',
    singers: ['Luis Fonsi', 'Daddy Yankee', 'Various'],
    artists: ['Luis Fonsi'],
    composers: ['Luis Fonsi'],
    lyricist: 'Luis Fonsi',
    releaseYear: 2017,
    genre: ['Party', 'Indie Hindi'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Despacito Hindi']
  },
  {
    title: 'Cheap Thrills (Hindi Cover)',
    movie: 'Single',
    singers: ['Sia', 'Sean Paul', 'Various'],
    artists: ['Sia'],
    composers: ['Greg Kurstin'],
    lyricist: 'Sia',
    releaseYear: 2016,
    genre: ['Party', 'Indie Hindi'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Cheap Thrills Hindi']
  },

  // -------------------------------------------------------------
  // 2000s (30+ songs)
  // -------------------------------------------------------------
  {
    title: 'Munni Badnaam Hui',
    movie: 'Dabangg',
    singers: ['Mamta Sharma', 'Aishwarya Nigam', 'Amit Kumar'],
    artists: ['Malaika Arora', 'Salman Khan'],
    composers: ['Lalit Pandit'],
    lyricist: 'Jalees Sherwani',
    releaseYear: 2010,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Munni Badnaam']
  },
  {
    title: 'Sheila Ki Jawani',
    movie: 'Tees Maar Khan',
    singers: ['Sunidhi Chauhan', 'Vishal Dadlani'],
    artists: ['Katrina Kaif'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Anvita Dutt',
    releaseYear: 2010,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['My Name Is Sheila']
  },
  {
    title: 'Ainvayi Ainvayi',
    movie: 'Band Baaja Baaraat',
    singers: ['Salim Merchant', 'Sunidhi Chauhan'],
    artists: ['Ranveer Singh', 'Anushka Sharma'],
    composers: ['Salim-Sulaiman'],
    lyricist: 'Amitabh Bhattacharya',
    releaseYear: 2010,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Main To Ainvayi Ainvayi Lut Gaya']
  },
  {
    title: 'Yeh Dooriyan',
    movie: 'Love Aaj Kal',
    singers: ['Mohit Chauhan'],
    artists: ['Saif Ali Khan', 'Deepika Padukone'],
    composers: ['Pritam'],
    lyricist: 'Irshad Kamil',
    releaseYear: 2009,
    genre: ['Sad', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Yeh Dooriyan In Raahon Ki Dooriyan']
  },
  {
    title: 'Dhan Te Nan',
    movie: 'Kaminey',
    singers: ['Sukhwinder Singh', 'Vishal Dadlani'],
    artists: ['Shahid Kapoor'],
    composers: ['Vishal Bhardwaj'],
    lyricist: 'Gulzar',
    releaseYear: 2009,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dhan Te Nan Aaja Aaja']
  },
  {
    title: 'Masakali',
    movie: 'Delhi-6',
    singers: ['Mohit Chauhan'],
    artists: ['Abhishek Bachchan', 'Sonam Kapoor'],
    composers: ['A. R. Rahman'],
    lyricist: 'Prasoon Joshi',
    releaseYear: 2009,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Masakali Masakali']
  },
  {
    title: 'Tujh Mein Rab Dikhta Hai',
    movie: 'Rab Ne Bana Di Jodi',
    singers: ['Roop Kumar Rathod'],
    artists: ['Shah Rukh Khan', 'Anushka Sharma'],
    composers: ['Salim-Sulaiman'],
    lyricist: 'Jaideep Sahni',
    releaseYear: 2008,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tujhme Rab Dikhta Hai']
  },
  {
    title: 'Jai Ho',
    movie: 'Slumdog Millionaire',
    singers: ['A. R. Rahman', 'Sukhwinder Singh', 'Tanvi Shah', 'Mahalakshmi Iyer', 'Vijay Prakash'],
    artists: ['Dev Patel', 'Freida Pinto'],
    composers: ['A. R. Rahman'],
    lyricist: 'Gulzar',
    releaseYear: 2008,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Jai Ho Slumdog']
  },
  {
    title: 'Khwaja Mere Khwaja',
    movie: 'Jodhaa Akbar',
    singers: ['A. R. Rahman'],
    artists: ['Hrithik Roshan', 'Aishwarya Rai Bachchan'],
    composers: ['A. R. Rahman'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2008,
    genre: ['Devotional', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Khwaja Ji']
  },
  {
    title: 'Jashn-E-Bahaaraa',
    movie: 'Jodhaa Akbar',
    singers: ['Javed Ali'],
    artists: ['Hrithik Roshan', 'Aishwarya Rai Bachchan'],
    composers: ['A. R. Rahman'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2008,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Jashn E Bahaara', 'Kehne Ko Jashn E Bahara Hai']
  },
  {
    title: 'Pappu Can\'t Dance',
    movie: 'Jaane Tu... Ya Jaane Na',
    singers: ['Benny Dayal', 'Naresh Iyer', 'Satish Chakravarthy', 'Aslam', 'Blaaze', 'Tanvi Shah', 'Bhargavi Pillai'],
    artists: ['Imran Khan', 'Genelia D\'Souza'],
    composers: ['A. R. Rahman'],
    lyricist: 'Abbas Tyrewala',
    releaseYear: 2008,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Pappu Can\'t Dance Saala']
  },
  {
    title: 'Dard-E-Disco',
    movie: 'Om Shanti Om',
    singers: ['Sukhwinder Singh', 'Marianne D\'Cruz', 'Nisha'],
    artists: ['Shah Rukh Khan'],
    composers: ['Vishal-Shekhar'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2007,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dard E Disco']
  },
  {
    title: 'Tere Bina',
    movie: 'Guru',
    singers: ['A. R. Rahman', 'Chinmayi', 'Murtuza Khan', 'Qadir Khan'],
    artists: ['Abhishek Bachchan', 'Aishwarya Rai Bachchan'],
    composers: ['A. R. Rahman'],
    lyricist: 'Gulzar',
    releaseYear: 2007,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tere Bina Beswadi']
  },
  {
    title: 'Chaand Sifarish',
    movie: 'Fanaa',
    singers: ['Shaan', 'Kailash Kher'],
    artists: ['Aamir Khan', 'Kajol'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Prasoon Joshi',
    releaseYear: 2006,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Subhanallah Chaand Sifarish']
  },
  {
    title: 'Rang De Basanti',
    movie: 'Rang De Basanti',
    singers: ['Daler Mehndi', 'K. S. Chithra'],
    artists: ['Aamir Khan'],
    composers: ['A. R. Rahman'],
    lyricist: 'Prasoon Joshi',
    releaseYear: 2006,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Rang De Basanti Title Track']
  },
  {
    title: 'Kajra Re',
    movie: 'Bunty Aur Babli',
    singers: ['Alisha Chinai', 'Javed Ali', 'Shankar Mahadevan'],
    artists: ['Aishwarya Rai Bachchan', 'Abhishek Bachchan', 'Amitabh Bachchan'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Gulzar',
    releaseYear: 2005,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kajra Re Kajra Re']
  },
  {
    title: 'Tumse Milke Dil Ka',
    movie: 'Main Hoon Na',
    singers: ['Sonu Nigam', 'Aftab Sabri', 'Hashim Sabri'],
    artists: ['Shah Rukh Khan', 'Sushmita Sen', 'Zayed Khan', 'Amrita Rao'],
    composers: ['Anu Malik'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2004,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tumse Milke Dil Ka Hai Jo Haal']
  },
  {
    title: 'Kal Ho Naa Ho',
    movie: 'Kal Ho Naa Ho',
    singers: ['Sonu Nigam'],
    artists: ['Shah Rukh Khan', 'Preity Zinta', 'Saif Ali Khan'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2003,
    genre: ['Sad', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Har Ghadi Badal Rahi Hai']
  },
  {
    title: 'Maahi Ve',
    movie: 'Kal Ho Naa Ho',
    singers: ['Sadhana Sargam', 'Sujata Bhattacharya', 'Udit Narayan', 'Sonu Nigam', 'Shankar Mahadevan'],
    artists: ['Shah Rukh Khan', 'Preity Zinta', 'Saif Ali Khan'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2003,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mahi Ve']
  },
  {
    title: 'It\'s The Time To Disco',
    movie: 'Kal Ho Naa Ho',
    singers: ['Vasundhara Das', 'KK', 'Shaan', 'Loy Mendonsa'],
    artists: ['Shah Rukh Khan', 'Preity Zinta', 'Saif Ali Khan'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2003,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Time To Disco']
  },
  {
    title: 'Suraj Hua Maddham',
    movie: 'Kabhi Khushi Kabhie Gham',
    singers: ['Sonu Nigam', 'Alka Yagnik'],
    artists: ['Shah Rukh Khan', 'Kajol'],
    composers: ['Sandesh Shandilya'],
    lyricist: 'Anil Pandey',
    releaseYear: 2001,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Suraj Hua Madham']
  },
  {
    title: 'Bole Chudiyan',
    movie: 'Kabhi Khushi Kabhie Gham',
    singers: ['Amit Kumar', 'Sonu Nigam', 'Alka Yagnik', 'Udit Narayan', 'Kavita Krishnamurthy'],
    artists: ['Amitabh Bachchan', 'Jaya Bachchan', 'Shah Rukh Khan', 'Kajol', 'Hrithik Roshan', 'Kareena Kapoor'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Sameer',
    releaseYear: 2001,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Bole Chudiyan Bole Kangna']
  },
  {
    title: 'You Are My Soniya',
    movie: 'Kabhi Khushi Kabhie Gham',
    singers: ['Sonu Nigam', 'Alka Yagnik'],
    artists: ['Hrithik Roshan', 'Kareena Kapoor'],
    composers: ['Sandesh Shandilya'],
    lyricist: 'Sameer',
    releaseYear: 2001,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dekha Tumko Jabse']
  },
  {
    title: 'Ek Pal Ka Jeena',
    movie: 'Kaho Naa... Pyaar Hai',
    singers: ['Lucky Ali'],
    artists: ['Hrithik Roshan', 'Ameesha Patel'],
    composers: ['Rajesh Roshan'],
    lyricist: 'Ibrahim Ashk',
    releaseYear: 2000,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ek Pal Ka Jeena Phir To Hai Jaana']
  },
  {
    title: 'Na Tum Jaano Na Hum',
    movie: 'Kaho Naa... Pyaar Hai',
    singers: ['Lucky Ali', 'Ramya'],
    artists: ['Hrithik Roshan', 'Ameesha Patel'],
    composers: ['Rajesh Roshan'],
    lyricist: 'Ibrahim Ashk',
    releaseYear: 2000,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kyun Chalti Hai Pawan']
  },
  
  // -------------------------------------------------------------
  // 1990s (25+ songs)
  // -------------------------------------------------------------
  {
    title: 'Taal Se Taal Mila',
    movie: 'Taal',
    singers: ['Alka Yagnik', 'Udit Narayan'],
    artists: ['Aishwarya Rai Bachchan', 'Akshaye Khanna'],
    composers: ['A. R. Rahman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1999,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Taal Se Taal Mila']
  },
  {
    title: 'Tadap Tadap',
    movie: 'Hum Dil De Chuke Sanam',
    singers: ['KK', 'Dominique Cerejo'],
    artists: ['Salman Khan', 'Aishwarya Rai Bachchan'],
    composers: ['Ismail Darbar'],
    lyricist: 'Mehboob',
    releaseYear: 1999,
    genre: ['Sad', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tadap Tadap Ke Is Dil Se']
  },
  {
    title: 'Nimbooda',
    movie: 'Hum Dil De Chuke Sanam',
    singers: ['Kavita Krishnamurthy', 'Karsan Sargathia'],
    artists: ['Aishwarya Rai Bachchan'],
    composers: ['Ismail Darbar'],
    lyricist: 'Mehboob',
    releaseYear: 1999,
    genre: ['Party', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Nimbuda Nimbuda']
  },
  {
    title: 'Chaiyya Chaiyya',
    movie: 'Dil Se..',
    singers: ['Sukhwinder Singh', 'Sapna Awasthi'],
    artists: ['Shah Rukh Khan', 'Malaika Arora'],
    composers: ['A. R. Rahman'],
    lyricist: 'Gulzar',
    releaseYear: 1998,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Chal Chaiyya Chaiyya']
  },
  {
    title: 'Dil Se Re',
    movie: 'Dil Se..',
    singers: ['A. R. Rahman', 'Anuradha Sriram', 'Anupama', 'Febi Mani'],
    artists: ['Shah Rukh Khan', 'Manisha Koirala'],
    composers: ['A. R. Rahman'],
    lyricist: 'Gulzar',
    releaseYear: 1998,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Se Re']
  },
  {
    title: 'Kuch Kuch Hota Hai',
    movie: 'Kuch Kuch Hota Hai',
    singers: ['Udit Narayan', 'Alka Yagnik'],
    artists: ['Shah Rukh Khan', 'Kajol', 'Rani Mukerji'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Sameer',
    releaseYear: 1998,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tum Paas Aaye']
  },
  {
    title: 'Saajanji Ghar Aaye',
    movie: 'Kuch Kuch Hota Hai',
    singers: ['Kumar Sanu', 'Alka Yagnik', 'Kavita Krishnamurthy'],
    artists: ['Salman Khan', 'Kajol'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Sameer',
    releaseYear: 1998,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Sajan Ji Ghar Aaye']
  },
  {
    title: 'Dil To Pagal Hai',
    movie: 'Dil To Pagal Hai',
    singers: ['Lata Mangeshkar', 'Udit Narayan'],
    artists: ['Shah Rukh Khan', 'Madhuri Dixit', 'Karisma Kapoor'],
    composers: ['Uttam Singh'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1997,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Toh Pagal Hai']
  },
  {
    title: 'Mehndi Laga Ke Rakhna',
    movie: 'Dilwale Dulhania Le Jayenge',
    singers: ['Lata Mangeshkar', 'Udit Narayan'],
    artists: ['Shah Rukh Khan', 'Kajol'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1995,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mehendi Laga Ke Rakhna']
  },
  {
    title: 'Tujhe Dekha To',
    movie: 'Dilwale Dulhania Le Jayenge',
    singers: ['Kumar Sanu', 'Lata Mangeshkar'],
    artists: ['Shah Rukh Khan', 'Kajol'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1995,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tujhe Dekha To Yeh Jaana Sanam']
  },
  {
    title: 'Zara Sa Jhoom Loon Main',
    movie: 'Dilwale Dulhania Le Jayenge',
    singers: ['Asha Bhosle', 'Abhijeet Bhattacharya'],
    artists: ['Shah Rukh Khan', 'Kajol'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1995,
    genre: ['Party', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Zara Sa Jhum Loon Main']
  },
  {
    title: 'Tu Cheez Badi Hai Mast Mast',
    movie: 'Mohra',
    singers: ['Udit Narayan', 'Kavita Krishnamurthy'],
    artists: ['Akshay Kumar', 'Raveena Tandon'],
    composers: ['Viju Shah'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1994,
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tu Cheez Badi Hai Mast']
  },
  {
    title: 'Tip Tip Barsa Paani',
    movie: 'Mohra',
    singers: ['Udit Narayan', 'Alka Yagnik'],
    artists: ['Akshay Kumar', 'Raveena Tandon'],
    composers: ['Viju Shah'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1994,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tip Tip Barsa Pani']
  },
  {
    title: 'Chura Ke Dil Mera',
    movie: 'Main Khiladi Tu Anari',
    singers: ['Kumar Sanu', 'Alka Yagnik'],
    artists: ['Akshay Kumar', 'Shilpa Shetty'],
    composers: ['Anu Malik'],
    lyricist: 'Rani Malik',
    releaseYear: 1994,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Chura Ke Dil Mera Goriya Chali']
  },
  {
    title: 'Pehla Nasha',
    movie: 'Jo Jeeta Wohi Sikandar',
    singers: ['Udit Narayan', 'Sadhana Sargam'],
    artists: ['Aamir Khan', 'Ayesha Jhulka'],
    composers: ['Jatin-Lalit'],
    lyricist: 'Majrooh Sultanpuri',
    releaseYear: 1992,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Pehla Nasha Pehla Khumar']
  },
  {
    title: 'Roja Jaaneman',
    movie: 'Roja',
    singers: ['S. P. Balasubrahmanyam', 'Sujatha Mohan'],
    artists: ['Arvind Swamy', 'Madhoo'],
    composers: ['A. R. Rahman'],
    lyricist: 'P.K. Mishra',
    releaseYear: 1992,
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Roja Janeman']
  },
  {
    title: 'Dil Chahta Hai',
    movie: 'Dil Chahta Hai',
    singers: ['Shankar Mahadevan', 'Clinton Cerejo'],
    artists: ['Aamir Khan', 'Saif Ali Khan', 'Akshaye Khanna'],
    composers: ['Shankar-Ehsaan-Loy'],
    lyricist: 'Javed Akhtar',
    releaseYear: 2001, // Pushed down to late 90s/early 00s mix requested
    genre: ['Party', 'Bollywood'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Chahta Hai Title Track']
  },
  {
    title: 'Kaho Na Kaho',
    movie: 'Murder',
    singers: ['Amir Jamal'],
    artists: ['Emraan Hashmi', 'Mallika Sherawat'],
    composers: ['Anu Malik'],
    lyricist: 'Sayeed Quadri',
    releaseYear: 2004, // Included in requested 90s mix list
    genre: ['Romantic', 'Bollywood'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kaho Na Kaho Yeh Aankhen Bolti Hain']
  },
  {
    title: 'O Sanam',
    movie: 'Sunoh',
    singers: ['Lucky Ali'],
    artists: ['Lucky Ali'],
    composers: ['Lucky Ali'],
    lyricist: 'Syed Aslam Noor',
    releaseYear: 1996,
    genre: ['Indie Hindi'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['O Sanam Mohabbat Ki Kasam']
  },
  {
    title: 'Ae Mere Humsafar',
    movie: 'Qayamat Se Qayamat Tak',
    singers: ['Udit Narayan', 'Alka Yagnik'],
    artists: ['Aamir Khan', 'Juhi Chawla'],
    composers: ['Anand-Milind'],
    lyricist: 'Majrooh Sultanpuri',
    releaseYear: 1988,
    genre: ['Romantic', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ae Mere Humsafar Ek Zara Intezaar']
  },
  {
    title: 'Papa Kehte Hain',
    movie: 'Qayamat Se Qayamat Tak',
    singers: ['Udit Narayan'],
    artists: ['Aamir Khan'],
    composers: ['Anand-Milind'],
    lyricist: 'Majrooh Sultanpuri',
    releaseYear: 1988,
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Papa Kehte Hain Bada Naam Karega']
  },

  // -------------------------------------------------------------
  // 1980s (15+ songs)
  // -------------------------------------------------------------
  {
    title: 'Dil Deewana',
    movie: 'Maine Pyar Kiya',
    singers: ['S. P. Balasubrahmanyam', 'Lata Mangeshkar'],
    artists: ['Salman Khan', 'Bhagyashree'],
    composers: ['Raamlaxman'],
    lyricist: 'Asad Bhopali',
    releaseYear: 1989,
    genre: ['Romantic', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dil Deewana Bin Sajna Ke']
  },
  {
    title: 'Kabootar Ja Ja Ja',
    movie: 'Maine Pyar Kiya',
    singers: ['S. P. Balasubrahmanyam', 'Lata Mangeshkar'],
    artists: ['Salman Khan', 'Bhagyashree'],
    composers: ['Raamlaxman'],
    lyricist: 'Dev Kohli',
    releaseYear: 1989,
    genre: ['Romantic', 'Retro'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kabootar Ja']
  },
  {
    title: 'Ek Do Teen',
    movie: 'Tezaab',
    singers: ['Alka Yagnik'],
    artists: ['Madhuri Dixit'],
    composers: ['Laxmikant-Pyarelal'],
    lyricist: 'Javed Akhtar',
    releaseYear: 1988,
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Ek Do Teen Char']
  },
  {
    title: 'Hawa Hawai',
    movie: 'Mr. India',
    singers: ['Kavita Krishnamurthy'],
    artists: ['Sridevi'],
    composers: ['Laxmikant-Pyarelal'],
    lyricist: 'Javed Akhtar',
    releaseYear: 1987,
    genre: ['Party', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Kehte Hain Mujhko Hawa Hawai']
  },
  {
    title: 'Agar Tum Na Hote',
    movie: 'Agar Tum Na Hote',
    singers: ['Kishore Kumar'],
    artists: ['Rajesh Khanna', 'Rekha'],
    composers: ['R. D. Burman'],
    lyricist: 'Gulshan Bawra',
    releaseYear: 1983,
    genre: ['Sad', 'Retro'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Humein Aur Jeene Ki Chahat Na Hoti']
  },
  {
    title: 'Pag Ghungroo Baandh',
    movie: 'Namak Halaal',
    singers: ['Kishore Kumar'],
    artists: ['Amitabh Bachchan'],
    composers: ['Bappi Lahiri'],
    lyricist: 'Anjaan',
    releaseYear: 1982,
    genre: ['Party', 'Retro'],
    difficulty: 4,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Pag Ghungroo']
  },
  {
    title: 'Om Shanti Om',
    movie: 'Karz',
    singers: ['Kishore Kumar'],
    artists: ['Rishi Kapoor'],
    composers: ['Laxmikant-Pyarelal'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1980,
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Meri Umar Ke Naujawano']
  },
  {
    title: 'Dhak Dhak Karne Laga',
    movie: 'Beta',
    singers: ['Udit Narayan', 'Anuradha Paudwal'],
    artists: ['Anil Kapoor', 'Madhuri Dixit'],
    composers: ['Anand-Milind'],
    lyricist: 'Sameer',
    releaseYear: 1992, // Included in user's 80s list mentally
    genre: ['Romantic', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Dhak Dhak']
  },
  {
    title: 'Jumma Chumma De De',
    movie: 'Hum',
    singers: ['Sudesh Bhosle', 'Kavita Krishnamurthy'],
    artists: ['Amitabh Bachchan', 'Kimi Katkar'],
    composers: ['Laxmikant-Pyarelal'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1991, // Close enough to 80s block
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Jumma Chumma']
  },
  {
    title: 'Tamma Tamma Loge',
    movie: 'Thanedaar',
    singers: ['Bappi Lahiri', 'Anuradha Paudwal'],
    artists: ['Sanjay Dutt', 'Madhuri Dixit'],
    composers: ['Bappi Lahiri'],
    lyricist: 'Indeevar',
    releaseYear: 1990,
    genre: ['Party', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tu Mera Hero']
  },

  // -------------------------------------------------------------
  // 1970s (10+ songs)
  // -------------------------------------------------------------
  {
    title: 'Yeh Dosti',
    movie: 'Sholay',
    singers: ['Kishore Kumar', 'Manna Dey'],
    artists: ['Amitabh Bachchan', 'Dharmendra'],
    composers: ['R. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1975,
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Yeh Dosti Hum Nahi Todenge']
  },
  {
    title: 'Mehbooba Mehbooba',
    movie: 'Sholay',
    singers: ['R. D. Burman'],
    artists: ['Helen', 'Jalal Agha'],
    composers: ['R. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1975,
    genre: ['Party', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['O Meri Mehbooba']
  },
  {
    title: 'Dum Maro Dum',
    movie: 'Hare Rama Hare Krishna',
    singers: ['Asha Bhosle'],
    artists: ['Zeenat Aman'],
    composers: ['R. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1971,
    genre: ['Party', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mit Jaye Gham']
  },
  {
    title: 'Yeh Sham Mastani',
    movie: 'Kati Patang',
    singers: ['Kishore Kumar'],
    artists: ['Rajesh Khanna', 'Asha Parekh'],
    composers: ['R. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1971,
    genre: ['Romantic', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Yeh Shaam Mastani']
  },
  {
    title: 'Chingari Koi Bhadke',
    movie: 'Amar Prem',
    singers: ['Kishore Kumar'],
    artists: ['Rajesh Khanna', 'Sharmila Tagore'],
    composers: ['R. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1972,
    genre: ['Sad', 'Retro'],
    difficulty: 3,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Chingari']
  },
  {
    title: 'Roop Tera Mastana',
    movie: 'Aradhana',
    singers: ['Kishore Kumar'],
    artists: ['Rajesh Khanna', 'Sharmila Tagore'],
    composers: ['S. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1969, // User put it in 70s, it's widely associated with 70s Kishore era
    genre: ['Romantic', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Roop Tera']
  },
  {
    title: 'Mere Sapno Ki Rani',
    movie: 'Aradhana',
    singers: ['Kishore Kumar'],
    artists: ['Rajesh Khanna', 'Sharmila Tagore'],
    composers: ['S. D. Burman'],
    lyricist: 'Anand Bakshi',
    releaseYear: 1969,
    genre: ['Romantic', 'Retro'],
    difficulty: 1,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Mere Sapnon Ki Rani Kab Aayegi Tu']
  },
  {
    title: 'Tera Mujhse Hai Pehle Ka',
    movie: 'Aa Gale Lag Jaa',
    singers: ['Kishore Kumar'],
    artists: ['Shashi Kapoor', 'Sharmila Tagore'],
    composers: ['R. D. Burman'],
    lyricist: 'Sahir Ludhianvi',
    releaseYear: 1973,
    genre: ['Romantic', 'Retro'],
    difficulty: 2,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Tera Mujhse Hai Pehle Ka Nata Koi']
  },
  {
    title: 'Koi Hota Jisko Apna',
    movie: 'Mere Apne',
    singers: ['Kishore Kumar'],
    artists: ['Vinod Khanna'],
    composers: ['Salil Chowdhury'],
    lyricist: 'Gulzar',
    releaseYear: 1971,
    genre: ['Sad', 'Retro'],
    difficulty: 4,
    audioPreviewUrl: '',
    artworkUrl: '',
    aliases: ['Koi Hota Jisko Apna Hum Apna Keh Lete Yaaro']
  }
];
